### ISSUE TITLE
URIError: URI malformed when password contains '%' character 

### ISSUE THREAD

**Issue by skotchio** [aheckmann/muri#10]
My connection string looks like this:

    mongodb://user:pass%@localhost:27017/site

When I execute `mongoose.connect(url)` I'm getting the following error:

    URIError: URI malformed

I also tried to encode login and pass first but due to the double decoding [here](https://github.com/aheckmann/muri/blob/master/lib/index.js#L64-L66) and [here](https://github.com/aheckmann/muri/blob/master/lib/index.js#L195-L196) I'm getting the same issue

**Comment by hugo-santos-imgtec** [comment]
I've experienced the same issue. 
Removing the % character from the connection string password, solved the issue for me.

**Comment by vkarpov15** [comment]
The [MongoDB connection spec](https://github.com/mongodb/specifications/blob/master/source/connection-string/connection-string-spec.rst#userinfo-optional) states that url and password **must** be URL encoded if they contain '%'. To have 'pass%' as your password, do `mongodb://user:pass%25@localhost:27017/site` because '%25' is the url encoding of '%'.

Sorry for the inconvenience, but this is something where muri and mongoose were off spec and needed to be changed.

**Comment by skotchio** [comment]
@vkarpov15. When decoding user and pass like this:

    const url = 'mongodb://' + encodeURIComponent('user') + ':' + encodeURIComponent('pass%') + '@localhost:27017/site';
    mongoose.connect(url);

the problem still exists due to the decoding them twice as I mentioned in my previous post [one here](https://github.com/aheckmann/muri/blob/master/lib/index.js#L64-L66) and [and once again here](https://github.com/aheckmann/muri/blob/master/lib/index.js#L195-L196).

Please try yourself and you'll see the issue.
